# Generated by Django 4.0.4 on 2022-05-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_product_image_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_dat',
            new_name='created_date',
        ),
    ]
